# Generated by Django 4.2.7 on 2024-12-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=300, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(help_text='Enter a unique name for the host.', max_length=300)),
                ('ip', models.GenericIPAddressField(help_text='Enter the IPv4 or IPv6 address of the host.')),
                ('port', models.IntegerField(default=22, help_text='Specify the port number for SSH connections (default is 22).')),
                ('username', models.CharField(help_text='Enter the username for authenticating with the host.', max_length=300)),
                ('password', models.CharField(blank=True, help_text='Enter the password for authentication. Leave blank if using a PEM file.', max_length=300, null=True)),
                ('pem_file', models.FileField(blank=True, help_text='Upload a PEM file for key-based authentication. Leave blank if using a password.', null=True, upload_to='pem_file/')),
                ('description', models.TextField(blank=True, help_text='Provide a brief description or notes about the host.', null=True)),
                ('connect_script', models.TextField(blank=True, help_text='Custom connect script to run. CAUTION: This script overrides the default connection script. Ensure that the script is secure and functions correctly.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalHost',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('extra_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.CharField(blank=True, max_length=300, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(help_text='Enter a unique name for the host.', max_length=300)),
                ('ip', models.GenericIPAddressField(help_text='Enter the IPv4 or IPv6 address of the host.')),
                ('port', models.IntegerField(default=22, help_text='Specify the port number for SSH connections (default is 22).')),
                ('username', models.CharField(help_text='Enter the username for authenticating with the host.', max_length=300)),
                ('password', models.CharField(blank=True, help_text='Enter the password for authentication. Leave blank if using a PEM file.', max_length=300, null=True)),
                ('pem_file', models.TextField(blank=True, help_text='Upload a PEM file for key-based authentication. Leave blank if using a password.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Provide a brief description or notes about the host.', null=True)),
                ('connect_script', models.TextField(blank=True, help_text='Custom connect script to run. CAUTION: This script overrides the default connection script. Ensure that the script is secure and functions correctly.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical host',
                'verbose_name_plural': 'historical hosts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
