# Generated by Django 4.2.7 on 2024-12-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_host_historicalhost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhost',
            name='connect_script',
        ),
        migrations.RemoveField(
            model_name='host',
            name='connect_script',
        ),
    ]
