# Generated by Django 5.0 on 2024-12-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_historicalhost_ip_remove_host_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhost',
            name='use_credential',
            field=models.CharField(choices=[('password', 'Password'), ('pem', 'PEM File')], default='pem', help_text='Specify whether to use a password or PEM file for authentication.', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalhost',
            name='username',
            field=models.CharField(default='ubuntu', help_text='Enter the username for authenticating with the host.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='use_credential',
            field=models.CharField(choices=[('password', 'Password'), ('pem', 'PEM File')], default='pem', help_text='Specify whether to use a password or PEM file for authentication.', max_length=10),
        ),
        migrations.AlterField(
            model_name='host',
            name='username',
            field=models.CharField(default='ubuntu', help_text='Enter the username for authenticating with the host.', max_length=300, null=True),
        ),
    ]
